version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: appsuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: student-backend:v1
    build: ./student-backend
    container_name: backend
    environment:
      DATABASE_URL: postgresql://appsuser:password123@db:5432/studentdb
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    image: student-frontend:v1
    build: ./student-frontend-ssr
    container_name: frontend
    environment:
      BACKEND_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run start

volumes:
  postgres_data: